
ARG NODE_VERSION=24.14.0-alpine
FROM node:${NODE_VERSION} AS dev

# Set working directory inside the container
WORKDIR /app

# Copy package files
COPY package.json yarn.lock ./
COPY vendor ./vendor

# Install dependencies
RUN yarn install --frozen-lockfile
 
# Copy rest of the source code
COPY . .
 
# Ensure the "node" user owns the application files
RUN chown -R node:node /app
 
# Switch to the built-in non-root "node" user
USER node
 
# Expose dev server port
EXPOSE 3003
 
# Run in dev mode, accessible outside the container
CMD ["yarn", "run", "start"]
